<?php
if ( ! function_exists( 'acf_add_local_field_group' ) ) {
    return;
}

acf_add_local_field_group( array(
    'key' => 'group_652e8ca8968cd',
    'title' => 'Tableau',
    'fields' => array(
        array(
            'key' => 'field_652e8ca9e5a71',
            'label' => 'Tableau',
            'name' => 'tableau',
            'aria-label' => '',
            'type' => 'table',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'use_header' => 1,
            'use_caption' => 2,
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'tableau',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
    'acfe_autosync' => '',
    'acfe_form' => 0,
    'acfe_display_title' => '',
    'acfe_meta' => '',
    'acfe_note' => '',
) );


register_post_type('tableau', array(
    'name' => 'tableau',
    'label' => 'Tableaux',
    'active' => true,
    'description' => '',
    'hierarchical' => false,
    'supports' => array(
        'title',
    ),
    'taxonomies' => array(),
    'public' => false,
    'exclude_from_search' => true,
    'publicly_queryable' => false,
    'can_export' => true,
    'delete_with_user' => null,
    'labels' => array(
        'singular_name' => 'Tableau',
        'add_new' => 'Ajouter',
        'add_new_item' => 'Ajouter un tableau',
        'edit_item' => 'Modifier',
        'new_item' => 'Nouveau',
        'view_item' => 'Voir',
        'view_items' => 'Voir les tableaux',
        'search_items' => 'Rechercher',
        'not_found' => 'Aucun résultât',
        'not_found_in_trash' => 'Aucun résultât dans la corbeille',
    ),
    'menu_position' => '',
    'menu_icon' => 'dashicons-editor-table',
    'show_ui' => true,
    'show_in_menu' => true,
    'show_in_nav_menus' => true,
    'show_in_admin_bar' => true,
    'has_archive' => false,
    'rewrite' => true,
    'capability_type' => 'post',
    'capabilities' => array(),
    'map_meta_cap' => null,
    'show_in_rest' => false,
    'rest_base' => '',
    'rest_controller_class' => 'WP_REST_Posts_Controller',
    'acfe_archive_template' => '',
    'acfe_archive_ppp' => 10,
    'acfe_archive_orderby' => 'date',
    'acfe_archive_order' => 'DESC',
    'acfe_archive_meta_key' => '',
    'acfe_archive_meta_type' => '',
    'acfe_single_template' => '',
    'acfe_admin_archive' => false,
    'acfe_admin_ppp' => 10,
    'acfe_admin_orderby' => 'date',
    'acfe_admin_order' => 'DESC',
    'acfe_admin_meta_key' => '',
    'acfe_admin_meta_type' => '',
    'acfe_autosync' => array(),
));

