<?php
if ( ! function_exists( 'acf_add_options_page' ) ) {
    return;
}

acf_add_options_page(array(
    'menu_slug' => 'informations-contact',
    'page_title' => 'Informations de contact',
    'active' => true,
    'menu_title' => 'Informations de contact',
    'capability' => 'edit_posts',
    'parent_slug' => 'options-general.php',
    'position' => 2,
    'icon_url' => '',
    'redirect' => true,
    'post_id' => 'informations_generales',
    'autoload' => false,
    'update_button' => 'Mise à jour',
    'updated_message' => 'Options mises à jour',
    'acfe_autosync' => array(),
));

add_action( 'acf/include_fields', function() {
    if ( ! function_exists( 'acf_add_local_field_group' ) ) {
        return;
    }

    acf_add_local_field_group( array(
        'key' => 'group_65685ec68d7f9',
        'title' => 'Informations de contact',
        'fields' => array(
            array(
                'key' => 'field_65685ec6ae117',
                'label' => 'Adresse',
                'name' => 'adresse',
                'aria-label' => '',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'acfe_textarea_code' => 0,
                'maxlength' => '',
                'rows' => '',
                'placeholder' => '',
                'new_lines' => '',
            ),
            array(
                'key' => 'field_65685f04ae118',
                'label' => 'Téléphone',
                'name' => 'telephone',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_65685f36ae119',
                'label' => 'Horaires',
                'name' => 'hours',
                'aria-label' => '',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'acfe_textarea_code' => 0,
                'maxlength' => '',
                'rows' => '',
                'placeholder' => '',
                'new_lines' => '',
            ),
            array(
                'key' => 'field_65685f6cae11a',
                'label' => 'Email',
                'name' => 'email',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_65685f82ae11b',
                'label' => 'Réseaux sociaux',
                'name' => 'reseaux_sociaux',
                'aria-label' => '',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'acfe_repeater_stylised_button' => 0,
                'layout' => 'table',
                'pagination' => 0,
                'min' => 0,
                'max' => 0,
                'collapsed' => '',
                'button_label' => 'Ajouter',
                'rows_per_page' => 20,
                'sub_fields' => array(
                    array(
                        'key' => 'field_65685f99ae11c',
                        'label' => 'Réseau social',
                        'name' => 'slug',
                        'aria-label' => '',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'facebook' => 'facebook',
                            'twitter' => 'twitter',
                            'instagram' => 'instagram',
                            'linkedin' => 'linkedin',
                        ),
                        'default_value' => false,
                        'return_format' => 'value',
                        'multiple' => 0,
                        'max' => '',
                        'prepend' => '',
                        'append' => '',
                        'allow_null' => 0,
                        'ui' => 0,
                        'ajax' => 0,
                        'placeholder' => '',
                        'allow_custom' => 0,
                        'search_placeholder' => '',
                        'min' => '',
                        'parent_repeater' => 'field_65685f82ae11b',
                    ),
                    array(
                        'key' => 'field_65685ff3ae11d',
                        'label' => 'URL',
                        'name' => 'url',
                        'aria-label' => '',
                        'type' => 'url',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'parent_repeater' => 'field_65685f82ae11b',
                    ),
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'informations-contact',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'left',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
        'acfe_autosync' => '',
        'acfe_form' => 0,
        'acfe_display_title' => '',
        'acfe_meta' => '',
        'acfe_note' => '',
    ) );
} );